sudo: required
      
services:
  - docker

before_install:
  - docker version

script:
  - ./scripts/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./scripts/deploy.sh
    fi
