version: 1.0.{build}
image: Visual Studio 2017 Preview

environment:
  DOCKER_USER:
    secure: kNQdvUM8df59Q0l9Gbvrbg==
  DOCKER_PASS:
    secure: SPi69AkfHhHUwGu46fus+w==

install:
  - ps: .\scripts\install.ps1

build_script:
  - ps: .\scripts\build.ps1

deploy_script:
  - ps: .\scripts\deploy.ps1
