version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: kNQdvUM8df59Q0l9Gbvrbg==
  DOCKER_PASS:
    secure: SPi69AkfHhHUwGu46fus+w==

install:
  - ps: Write-Host Server version $(gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').BuildLabEx
  - docker version

build_script:
  - ps: .\build.ps1

deploy_script:
  - ps: .\deploy.ps1
